00:44:41 Settings    Loaded configuration.json successfully
00:44:41 SQL Server  Please enter login info
00:45:04 SetConnecti New connection string set
00:45:04 Database Te Connection to database is valid
00:45:04 TODO        make it so functions that use db check if db is enabled in settings
00:45:04 Discord     Discord.Net v1.0.2 (API v6)
00:45:05 Gateway     Connecting
00:45:06 Gateway     Connected
00:45:06 Gateway     Ready
00:46:02 Gateway     A MessageReceived handler is blocking the gateway task.
00:46:02 Gateway     A MessageReceived handler has thrown an unhandled exception.:
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'Users.lcsbotDatabase' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at lcsbot.Services.SqlHandler.GetDataBaseFields(String tableName, String databaseName) in C:\Users\cPC\Dropbox\LCSBot\LCSBot\lcsbot\Services\SqlHandler.cs:line 101
   at lcsbot.Services.SqlHandler.Select(String tableName, String selectQuery, String condition, String databaseName) in C:\Users\cPC\Dropbox\LCSBot\LCSBot\lcsbot\Services\SqlHandler.cs:line 200
   at lcsbot.Functions.CheckUserInDatabase.Check(String userId) in C:\Users\cPC\Dropbox\LCSBot\LCSBot\lcsbot\Functions\CheckUserInDatabase.cs:line 15
   at lcsbot.Program.<HandleCommandAsync>d__4.MoveNext() in C:\Users\cPC\Dropbox\LCSBot\LCSBot\lcsbot\Program.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__128.MoveNext()
00:46:02 Gateway     System.Exception: WebSocket connection was closed ---> Discord.Net.WebSocketClosedException: The server sent close 1000: ""
   at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()
00:46:03 Gateway     Disconnecting
00:46:03 Gateway     Disconnected
00:46:04 Gateway     Connecting
00:46:05 Gateway     Resumed previous session
00:47:10 Gateway     Connected
00:47:10 Gateway     System.Exception: WebSocket connection was closed ---> Discord.Net.WebSocketClosedException: The server sent close 1000: ""
   at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()
00:47:10 Gateway     Disconnecting
00:47:10 Gateway     Disconnected
00:47:11 Gateway     Connecting
00:47:11 Gateway     Resumed previous session
